- name: "Create 'args' from the 'sheet'"
  ansible.builtin.set_fact:
    args: >-
      {{ (ansible_facts['sbce_config']

           | select('contains', sheet) 
           | first)[sheet] }}

- name: "Normalize OVA/OVF path (expand ~)"
  ansible.builtin.set_fact:
    ovf_path: "{{ (args.ovf | string) | regex_replace('^~', lookup('ansible.builtin.env', 'HOME')) }}"

- name: "Build OVA network mapping"
  ansible.builtin.set_fact:
    ovf_networks: >-
      {%- set result = {} -%}
      {%- for k in ['M1', 'B1', 'A2', 'B2', 'A1', 'M2'] -%}
        {%- if args[k] is defined and args[k] -%}
          {%- set _ = result.update({k: args[k]}) -%}
        {%- endif -%}
      {%- endfor -%}
      {{ result }}

- name: "Deploy SBCE OVA"
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ args.platform_address }}"
    username: "{{ args.platform_username }}"
    password: "{{ args.platform_password }}"
    #datacenter: "ha-datacenter"
    datastore: "{{ args.datastore }}"
    name: "{{ args.vmname }}"
    ovf: "{{ ovf_path }}"
    networks: "{{ ovf_networks }}"
    power_on: false
    wait_for_ip_address: false
    validate_certs: false
  delegate_to: localhost

- name: "Add NICs to SBCE VM"
  community.vmware.vmware_guest_network:
    hostname: "{{ args.platform_address }}"
    username: "{{ args.platform_username }}"
    password: "{{ args.platform_password }}"
    name: "{{ args.vmname }}"
    network_name: "{{ args[item] }}"
    state: present
    device_type: vmxnet3
    validate_certs: false
    force: true
  loop: "{{ ovf_networks.keys() | reject('equalto', 'M1') | list }}"
  when: ovf_networks[item] is defined and ovf_networks[item] | length > 0

- name: "Power-ON the VM"
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ args.platform_address }}"
    username: "{{ args.platform_username }}"
    password: "{{ args.platform_password }}"
    name: "{{ args.vmname }}"
    state: powered-on
    validate_certs: false

- name: Wait 240 seconds for VM to boot up
  ansible.builtin.pause:
    seconds: 240
