- name: "Create 'args' from the 'sheet'"
  ansible.builtin.set_fact:
    args: >-
      {{ (ansible_facts['sbce_config']
          | select('contains', sheet)
          | first)[sheet] }}
  tags:
    - always
    - step02
    - step02s1

- name: "Step 02a: Console bootstrap"
  ansible.builtin.include_tasks: 02a_console_bootstrap.yml
  tags:
    - always
    - step02
    - step02a
    - step02a0

- name: "Step 02b: Post bootstrap configuration"
  ansible.builtin.include_tasks: 02b_post_bootstrap_configuration.yml
  tags:
    - always
    - step02
    - step02b
    - step02b0

- name: "Step 02c: WebUI bootstrap"
  ansible.builtin.include_tasks: 02c_webui_bootstrap.yml
  when:
    - args.apptype in ('EMS', 'EMS+SBCE')
    - args.ems_inst_type | default('primary', true) != 'secondary'
  tags:
    - always
    - step02
    - step02c
    - step02c0
