- name: "Run deploy and install for {{ node_sheet }}"
  ansible.builtin.include_tasks:
    file: run_node_install.yml
  tags:
    - always
    - step01
    - step01a
    - step01b
    - step01c
    - step02
    - step02a
    - step02b
    - step02c
    - fullnode1

- name: "Step 03: Web UI configuration for {{ node_sheet }}"
  ansible.builtin.include_tasks:
    file: 03_webui_configuration.yml
  vars:
    sheet: "{{ node_sheet }}"
  tags:
    - always
    - step03
    - step03a
    - fullnode2
