---
all:
  children:
    ESXI:
      hosts:
        esxi1:
          ansible_host: 192.168.200.161
        esxi2:
          ansible_host: 192.168.200.162
      vars:
        ansible_user: root
        ansible_password: cmb@Dm1n
        python_interpreter: /bin/python3.8
    SBCE:
      hosts:
        EMS:
          ansible_host: 10.10.48.180
      vars:
        ansible_user: ipcs
        ansible_password: sbc10_cmb@Dm1n
...