- name: "Debug ordered_install_list"
  ansible.builtin.debug:
    var: ordered_install_list

- name: "Debug ems_nodes"
  ansible.builtin.debug:
    var: ems_nodes

- name: "Create 'args' from the 'sheet'"
  ansible.builtin.set_fact:
    args: >-
      {{ (ansible_facts['sbce_config']
          | select('contains', sheet)
          | first)[sheet] }}

