---
- hosts: localhost
  gather_facts: false

  vars:
    execution_dir: "{{ lookup('ansible.builtin.env', 'PWD') }}"
    sleep_time: 2

  tasks:
    - name: "Fail if 'src' file argument is not in --extra-vars"
      ansible.builtin.fail:
        msg: "'src' argument is missing"
      when: src is not defined
      changed_when: false
      tags:
        - always
        - setup1

    - name: "Expand 'src' to 'src_path'"
      ansible.builtin.set_fact:
        src_path: >-
          {{ src if src.startswith('/')
             else (execution_dir ~ '/' ~ src) | realpath }}
      tags:
        - always
        - setup2

    - name: "Verify 'src_path' exists"
      ansible.builtin.stat:
        path: "{{ src_path }}"
      register: src_stat_result
      failed_when: not src_stat_result.stat.exists
      tags:
        - always
        - setup3

    - name: "Step 00: Parse configuration"
      ansible.builtin.include_tasks:
        file: includes/00_parse_config.yml
      tags:
        - always
        - step00
        - step000

    - name: "Deploy, install, and configure EMS+SBCE nodes"
      ansible.builtin.include_tasks:
        file: includes/run_full_node.yml
      loop: "{{ coresident_install_list }}"
      loop_control:
        loop_var: node_sheet
      tags:
        - always
        - step01
        - step01a
        - step01b
        - step01c
        - step02
        - step02a
        - step02b
        - step02c
        - step03
        - step03a
        - coresident1

    - name: "Deploy EMS batches"
      ansible.builtin.include_tasks:
        file: includes/run_ems_batch.yml
      loop: "{{ primary_ems_install_list }}"
      loop_control:
        loop_var: ems_sheet
      tags:
        - always
        - step01
        - step01a
        - step01b
        - step01c
        - step02
        - step02a
        - step02b
        - step02c
        - step03
        - step03a
        - emsbatches1
