---
- name: "Add Web UI unit to EMS {{ ems_node.hostname }}"
  vars:
    add_unit: "{{ webui_unit | default(sbce_unit) }}"
    primary_child: "{{ add_unit.nodes[0] }}"
    secondary_child: "{{ add_unit.nodes[1] if add_unit.type == 'ha' else {} }}"
    add_node_type: "{{ 'ha' if add_unit.type == 'ha' else 'ems' if add_unit.type == 'ems' else 'sbce' }}"
    add_node_name: >-
      {{
        primary_child.appname
        if add_unit.type == 'ems' and (primary_child.appname | default('', true) | string | length > 0)
        else primary_child.vmname
      }}
    add_node_argv: >-
      {{
        [
          '--add-node',
          '--host', ems_node.ip0,
          '--ucsec-password', ems_node.ucsecpass,
          '--type', add_node_type,
          '--name', add_node_name,
          '--ip', primary_child.ip0,
          '--debug'
        ]
        + ([ '--name2', secondary_child.vmname, '--ip2', secondary_child.ip0 ] if add_unit.type == 'ha' else [])
      }}
  sbce_web_bootstrap:
    argv: "{{ add_node_argv }}"
  delegate_to: localhost
