- name: "Debug 'sheet'"
  debug:
    var: sheet

- name: "Wait 180 seconds for initialization to complete"
  ansible.builtin.pause:
    seconds: 180

- name: Send "1" to configure command line mode
  community.vmware.vmware_guest_sendkey:
    hostname: "{{ args.platform_address }}"
    username: "{{ args.platform_username }}"
    password: "{{ args.platform_password }}"
    name: "{{ args.vmname }}"
    name: "SBCE-VM"
    string_send: "1"
    validate_certs: false
