---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: "Fail if 'sbce_config' file argument is not in --extra-vars"
      ansible.builtin.fail:
        msg: "'sbce_config' file argument is not in --extra-vars"
      when: sbce_config is not defined

    - name: Run PLAY parse_sbce_config.yml
      include_tasks: parse_sbce_config.yml

    - name: Display args data
      ansible.builtin.debug:
        var: args

...